import 'dart:async';
import 'dart:math';

class ListWorks{
    final List<String> _dailyWorks = [
    "O fracasso é apenas uma oportunidade para recomeçar de forma mais inteligente.",
    "Seja corajoso o suficiente para seguir seu coração e sua intuição.",
    "Lembre-se de que cada novo dia é uma nova chance de fazer a diferença.",
    "Acredite em si mesmo, pois ninguém pode fazer isso por você.",
    "Não deixe que o medo do fracasso impeça você de tentar.",
    "A jornada para o sucesso pode ser difícil, mas cada obstáculo é uma oportunidade de crescimento.",
    "O único limite para suas conquistas é a sua imaginação.",
    "Não espere pelas condições perfeitas; comece onde você está com o que tem.",
    "Seja grato pelo que você tem enquanto trabalha pelo que deseja.",
    "Sucesso é a soma de pequenos esforços repetidos diariamente.",
    "Não desista quando as coisas ficarem difíceis; lembre-se de por que você começou.",
    "Acredite que você é capaz de superar qualquer desafio que surgir em seu caminho.",
    "Não tenha medo de falhar, tenha medo de não tentar.",
    "Você é mais forte do que imagina e capaz de alcançar coisas incríveis.",
    "O sucesso é uma questão de perseverança e determinação.",
    "Em vez de reclamar sobre os problemas, concentre-se em encontrar soluções.",
    "O único momento em que é tarde demais para começar é quando você desiste.",
    "Mantenha sua mente focada nos objetivos e seus pés firmes no chão.",
    "Lembre-se de que cada obstáculo é uma oportunidade para crescer e aprender.",
    "Não se compare a outras pessoas; sua jornada é única e especial.",
    "As dificuldades são apenas oportunidades disfarçadas.",
    "Confie em sua intuição; ela sabe o caminho certo a seguir.",
    "Não permita que as opiniões dos outros definam quem você é ou o que você pode alcançar.",
    "O sucesso não é um destino, é uma jornada contínua.",
    "Faça hoje o que os outros não estão dispostos a fazer para ter amanhã o que os outros não terão.",
    "Os erros são parte do processo de aprendizado e crescimento.",
    "O sucesso não acontece por acaso; é o resultado de trabalho árduo e dedicação.",
    "Lembre-se de que você é responsável pelo seu próprio sucesso e felicidade.",
    "Acredite em si mesmo, mesmo quando ninguém mais acredita.",
    "Não importa quantas vezes você caia, levante-se novamente e continue.",
    "Em vez de reclamar sobre as circunstâncias, tome ações para mudá-las.",
    "Não deixe que os fracassos do passado impeçam você de alcançar o sucesso futuro.",
    "Seja a mudança que você deseja ver no mundo.",
    "O sucesso é a soma de pequenos esforços feitos repetidamente.",
    "Acredite que você tem o poder de criar a vida que deseja viver.",
    "Encontre motivação nas pequenas coisas e celebre cada conquista.",
      "Em vez de reclamar sobre as circunstâncias, tome ações para mudá-las.",
      "Não deixe que os fracassos do passado impeçam você de alcançar o sucesso futuro.",
      "Seja a mudança que você deseja ver no mundo.",
      "O sucesso é a soma de pequenos esforços feitos repetidamente.",
      "Acredite que você tem o poder de criar a vida que deseja viver.",
      "Encontre motivação nas pequenas coisas e celebre cada conquista.",
      "Não se preocupe com o que os outros pensam; siga sua própria paixão.",
      "O otimismo é a chave para superar os desafios e encontrar soluções.",
      "Não permita que o passado determine seu futuro; cada dia é uma nova oportunidade.",
      "Seja a pessoa que você gostaria de ter ao seu lado em todos os momentos.",
      "Não desista apenas porque as coisas estão difíceis; a recompensa será ainda maior.",
      "Visualize seu sucesso e trabalhe todos os dias para alcançá-lo.",
      "O sucesso não é uma linha reta; haverá altos e baixos ao longo do caminho.",
      "Acredite em si mesmo, mesmo quando ninguém mais acredita.",
      "Não deixe que o medo do desconhecido impeça você de explorar novas oportunidades.",
      "Seja grato pelo presente e mantenha-se otimista em relação ao futuro.",
      "Aprenda com o passado, viva no presente e sonhe com o futuro.",
      "Mantenha o foco em seus objetivos, mesmo quando as coisas parecerem impossíveis.",
      "O sucesso não é medido pelo dinheiro que você tem, mas pela diferença que você faz na vida dos outros.",
      "Acredite em si mesmo, pois essa é a primeira chave para o sucesso.",
      "A única maneira de fazer um trabalho incrível é amar o que você faz.",
      "Não tenha medo de sair da sua zona de conforto e buscar novos desafios.",
      "Não permita que o passado defina seu futuro; cada dia é uma nova oportunidade.",
      "Seja a mudança que você deseja ver no mundo.",
      "O sucesso é a soma de pequenos esforços repetidos diariamente.",
      "Não se compare a outras pessoas; sua jornada é única e especial.",
      "Não espere por uma oportunidade, crie-a.",
      "O sucesso é uma questão de perseverança e determinação.",
      "Não deixe que o medo do fracasso impeça você de tentar.",
      "Acredite em si mesmo, mesmo quando ninguém mais acredita.",
      "Seja grato pelo que você tem enquanto trabalha pelo que deseja.",
      "Lembre-se de que cada obstáculo é uma oportunidade para crescer e aprender.",
      "O único limite para suas conquistas é a sua imaginação.",
      "Não desista quando as coisas ficarem difíceis; lembre-se de por que você começou.",
      "Acredite que você é capaz de superar qualquer desafio que surgir em seu caminho.",
      "Não tenha medo de falhar, tenha medo de não tentar.",
      "Você é mais forte do que imagina e capaz de alcançar coisas incríveis.",
      "O sucesso é uma jornada, não um destino.",
      "Mantenha sua mente focada nos objetivos e seus pés firmes no chão.",
      "Lembre-se de que cada obstáculo é uma oportunidade para crescer e aprender.",
      "O fracasso não é o fim, mas apenas uma lição no caminho para o sucesso.",
      "Mantenha-se determinado e persistente, mesmo quando as coisas ficarem difíceis.",
      "Não se preocupe com o que os outros pensam; siga seu próprio caminho.",
      "Acredite em si mesmo e em suas habilidades; você é capaz de grandes realizações.",
      "Não permita que o medo do desconhecido impeça você de explorar novas oportunidades.",
      "Concentre-se no progresso, não na perfeição.",
      "O sucesso é a soma de pequenos esforços repetidos diariamente.",
      "Não desista quando as coisas ficarem difíceis; lembre-se de por que você começou.",
      "Acredite que você é capaz de superar qualquer desafio que surgir em seu caminho.",
      "O único limite para suas conquistas é a sua imaginação.",
      "Não tenha medo de falhar, tenha medo de não tentar.",
      "Você é mais forte do que imagina e capaz de alcançar coisas incríveis.",
      "Acredite em si mesmo, mesmo quando ninguém mais acredita.",
      "Seja grato pelo que você tem enquanto trabalha pelo que deseja.",
      "Lembre-se de que cada obstáculo é uma oportunidade para crescer e aprender.",
      "O sucesso não é medido pelo dinheiro que você tem, mas pela diferença que você faz na vida dos outros.",
      "Acredite em si mesmo, pois essa é a primeira chave para o sucesso.",
      "A única maneira de fazer um trabalho incrível é amar o que você faz.",
      "Não tenha medo de sair da sua zona de conforto e buscar novos desafios.",
      "Seja grato pelo presente e mantenha-se otimista em relação ao futuro.",
      "Aprenda com o passado, viva no presente e sonhe com o futuro.",
      "Mantenha o foco em seus objetivos, mesmo quando as coisas parecerem impossíveis.",
      "O sucesso não é medido pelo dinheiro que você tem, mas pela diferença que você faz na vida dos outros.",
      "Acredite em si mesmo, pois essa é a primeira chave para o sucesso.",
      "A única maneira de fazer um trabalho incrível é amar o que você faz.",
      "Não tenha medo de sair da sua zona de conforto e buscar novos desafios.",
      "Não permita que o passado defina seu futuro; cada dia é uma nova oportunidade.",
      "Seja a mudança que você deseja ver no mundo.",
      "O sucesso é a soma de pequenos esforços repetidos diariamente.",
      "Espero que essas palavras motivacionais tenham inspirado você a alcançar seus objetivos e acreditar em si mesmo. Lembre-se sempre de que você é capaz de coisas incríveis.",
      "Mantenha-se focado em suas metas e não desvie do caminho.",
      "Grandes conquistas exigem grandes esforços. Não tenha medo de se dedicar.",
      "O sucesso não é determinado pelo número de falhas, mas pela capacidade de se levantar após cada uma delas.",
      "Não espere a motivação vir até você, crie-a todos os dias.",
      "Acredite em si mesmo mesmo quando ninguém mais acreditar. Você tem o poder de provar o contrário.",
      "Seja grato pelos desafios, pois são eles que o tornam mais forte e resiliente.",
      "Não permita que os obstáculos o impeçam de alcançar seus sonhos. Supere-os um de cada vez.",
      "Não tenha medo de começar pequeno. Todo progresso começa com um simples passo.",
      "Transforme seus fracassos em lições e use-os como degraus para o sucesso.",
      "A única maneira de alcançar grandes coisas é acreditar que você pode.",
      "Não se compare com os outros. Sua jornada é única e não pode ser comparada.",
      "Concentre-se em seu progresso, não nas comparações com os outros.",
      "O sucesso é construído sobre a consistência e a persistência.",
      "Esteja disposto a sair da sua zona de conforto para alcançar o crescimento pessoal.",
      "Seja paciente. O sucesso leva tempo, esforço e dedicação.",
      "Acredite que você merece o sucesso e trabalhe duro para alcançá-lo.",
      "Não permita que as opiniões negativas dos outros o afetem. Você sabe o que é melhor para si mesmo.",
      "Mantenha-se motivado mesmo nos momentos de desânimo. Esses são os momentos em que você mais precisa persistir.",
      "Transforme os problemas em oportunidades de crescimento e aprendizado.",
      "A vida é curta demais para desperdiçar seu potencial. Aproveite ao máximo cada dia.",
      "Acredite que você é capaz de superar qualquer obstáculo que surgir em seu caminho.",
      "Celebre suas pequenas vitórias ao longo do caminho. Cada conquista conta.",
      "Não deixe que o medo do fracasso o impeça de buscar seus sonhos.",
      "Permaneça fiel a si mesmo e aos seus valores, mesmo quando enfrentar adversidades.",
      "Tenha coragem para tomar as decisões necessárias para alcançar o sucesso.",
      "O sucesso não é uma linha reta. Aceite os altos e baixos do caminho e continue avançando.",
      "Não permita que as críticas o desanimem. Use-as como combustível para provar que estão erradas.",
      "Cultive uma mentalidade positiva e veja as oportunidades onde outros veem problemas.",
      "Não adie suas metas. Comece hoje mesmo a trabalhar para alcançá-las.",
      "Acredite que você merece ser feliz e bem-sucedido. Não aceite menos do que você merece.",
      "Mantenha-se perseverante mesmo quando tudo parecer difícil. A persistência é a chave para o sucesso.",
      "Aceite os desafios como oportunidades de crescimento e mostre ao mundo do que você é capaz.",
      "Não desista quando as coisas ficarem difíceis. É nesses momentos que você está mais próximo do sucesso.",
      "Seja gentil consigo mesmo e celebre suas realizações, por menores que sejam.",
      "Encontre a motivação dentro de você e use-a para impulsionar seus sonhos.",
      "Não deixe que as falhas definam sua jornada. Use-as como aprendizado e siga em frente.",
      "Mantenha-se focado em suas metas e não se distraia com o que os outros estão fazendo.",
      "Acredite em seu potencial ilimitado e nunca duvide de suas capacidades.",
      "Seja resiliente em face dos obstáculos e mostre ao mundo que você é inquebrável.",
      "Mantenha uma mentalidade aberta e esteja disposto a aprender com os outros.",
      "Transforme seus medos em coragem e veja as oportunidades que estão além deles.",
      "Não deixe que as opiniões negativas o desviem de seu caminho. Acredite em si mesmo.",
      "A vida é curta demais para se contentar com menos do que você é capaz de alcançar.",
      "Cultive a gratidão e encontre alegria nas pequenas coisas da vida.",
      "Seja o capitão de seu próprio navio e direcione sua vida na direção que deseja seguir.",
      "Acredite que você é digno de amor, sucesso e felicidade. Não aceite menos do que você merece.",
      "Mantenha a positividade mesmo quando as circunstâncias parecerem sombrias. A luz está dentro de você.",
      "Use seu passado como uma lição, não como um fardo. O que importa é o que você faz com o presente.",
      "Não deixe que as desculpas o impeçam de alcançar seu pleno potencial. Assuma a responsabilidade por sua vida.",
      "Não se compare aos outros, mas seja inspirado por eles. Cada pessoa tem uma jornada única.",
      "Aceite os fracassos como parte do processo de crescimento. Aprenda com eles e siga em frente.",
      "Não subestime seu próprio poder e capacidade de causar impacto no mundo.",
      "Mantenha uma atitude de gratidão e apreciação pelas oportunidades que a vida lhe oferece.",
      "Tenha confiança em suas habilidades e confie em sua intuição. Você sabe o que é melhor para si mesmo.",
      "Não deixe que o medo do desconhecido o impeça de explorar novos horizontes.",
      "Acredite que você é capaz de superar qualquer desafio que surgir em seu caminho.",
      "Não tenha medo de falhar, pois cada falha é uma oportunidade de aprender e crescer.",
      "Seja resiliente e persistente mesmo quando as coisas parecerem impossíveis. Você pode surpreender a si mesmo.",
      "Aceite a responsabilidade por sua vida e ações. Você tem o poder de moldar seu próprio destino.",
      "Lembre-se de que cada pequeno passo em direção a seus objetivos conta. Não subestime o poder da consistência.",
      "Acredite em seu próprio potencial e mantenha-se firme em sua visão, mesmo quando ninguém mais acreditar.",
      "A vida é cheia de altos e baixos, mas o importante é como você reage a eles. Escolha ser forte e persistente.",
      "Não se preocupe com o que os outros pensam de você. Foque em ser a melhor versão de si mesmo.",
      "Não espere a perfeição para começar. Comece agora e ajuste o curso ao longo do caminho.",
      "Mantenha-se curioso e sempre em busca de novos conhecimentos e experiências.",
      "Seja flexível em sua abordagem, mas firme em sua determinação de alcançar seus objetivos.",
      "Acredite que cada obstáculo que você supera o torna mais forte e mais preparado para o sucesso.",
      "Não deixe que o passado defina seu futuro. Cada dia é uma nova oportunidade para recomeçar.",
      "Cultive a paciência e aprenda a aproveitar o processo, não apenas o resultado final.",
      "Encontre a motivação em seu propósito de vida e deixe-o guiar suas ações.",
      "Não se compare com os outros, mas se inspire em suas conquistas e use-as como estímulo.",
      "Não tenha medo de correr riscos calculados. Grandes recompensas vêm para aqueles que ousam.",
      "Acredite que você é digno de amor, sucesso e felicidade. Não aceite menos do que você merece.",
      "Esteja disposto a enfrentar o desconforto temporário em busca de um futuro melhor.",
      "Não deixe que os obstáculos o desanimem. Eles são apenas desafios que testarão sua determinação.",
      "Seja gentil consigo mesmo e pratique a autocompaixão em tempos de dificuldade.",
    ];


    String getRandomWork(){
      Random random = Random();
      int randomNumber = random.nextInt(_dailyWorks.length);
      return _dailyWorks[randomNumber];
    }

}

